services:
  cobot_db:
    image: mariadb:10.11
    container_name: cobot_db
    restart: always

    env_file:
      - path: .env
        required: false

    environment:
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_USER: ${DB_USER}
      MARIADB_DATABASE: ${DB_DATABASE}

    ports:
    - ${DB_PORT}:3306

    volumes:
      - db_cobot:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "127.0.0.1", "-u${DB_USER}", "-p${DB_PASSWORD}"]

  backend:
    build: ./backend
    container_name: cobot_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - path: .env
    environment:
      - PYTHONUNBUFFERED=1
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: /app/backend
    volumes:
      - ./backend:/app
      - /app/.venv
    depends_on:
      cobot_db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: cobot_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - path: .env

volumes:
  db_cobot:
